
build:
  version: "1.0"

card:
  message: "Welcome to Card related prod APIs "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "aishwarya@bank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384