
  config:
    import:
      - "loan_qa.yml"
      - "loan_prod.yml"

  profiles:
      active:
        - "qa"

build:
  version: 1.0

loan:
  message: "Welcome to the loan Service"
  contact-details:
    email: "BkM9g@example.com"
    name: "Loan Team"
  onCallSupport:
    -(+91) 54646436565
    -(+91) 54646436565


