services:
  accountsdb:
    image: mysql
    container_name: accountsdb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "Sql@4567"
      MYSQL_DATABASE: "accountsdb"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-deploy-service
  cardsdb:
    image: mysql
    container_name: cardsdb
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "Sql@4567"
      MYSQL_DATABASE: "cardsdb"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-deploy-service
  loansdb:
    image: mysql
    container_name: loansdb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "Sql@4567"
      MYSQL_DATABASE: "loansdb"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-deploy-service
  configserver:
    image: "docker6758/configserver:s6"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "docker6758/accounts:s6"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "docker6758/loan:s6"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loan"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3308/loansdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "eazybytes/cards:s6"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3307/cardsdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  bankNetwork:
    driver: "bridge"
rf