spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #   active: native
  cloud:
    config:
      server:
        git:
#        native:
#          search-locations: "file:///C://config"
          uri: https://github.com/Saurabh12325/cloud-config-main.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#          search-locations: "classpath:/Config"

server:
  port: 8071
encrypt:
  key: "23kjdBJBnIUGfrUNFKGNjn3245"
